server:
   port: 8761
spring:
  application:
    name: abctest-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
logging: 
#  config: classpath:com/nantian/abctest/core/aop/log/logback-spring.xml
  file: ./log/${spring.application.name}.log
  level:
    root: INFO